{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pacc.fullname" . }}-mysql
  labels:
    app: pacc-mysql
    {{- include "pacc.labels" . | nindent 4 }}
spec:
  selector: { app: pacc-mysql }
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
{{- end }}