<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PaccManager</RootNamespace>
    <AssemblyName>PaccManager</AssemblyName>
    <Product>PACC Windows 管理工具</Product>
    <Version>4.2.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Update="app.manifest" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>